In [1]:
import numpy as np 

In [2]:
a = np.array([1, 2, 3 ])

In [3]:
a

array([1, 2, 3])

In [4]:
print(a)

[1 2 3]


In [6]:
b = np.array([[9, 10, 11.0], [7.0, 6, 5.0 ]])
print(b)

[[ 9. 10. 11.]
 [ 7.  6.  5.]]


In [8]:
#get dimensional for a and b 
print(a.ndim)
b.ndim

1


2

In [9]:
a.shape

(3,)

In [10]:
b.shape

(2, 3)

In [11]:
#get data type 
b.dtype #will give float64 because of float number

dtype('float64')

In [12]:
a.dtype #will give int32 because integer 

dtype('int32')

In [14]:
a.itemsize #because 32/8 is 4 bytes

4

In [15]:
32/8

4.0

In [17]:
b.itemsize

8

In [18]:
# get total size 
a.size  #give number of item 

3

In [20]:
a.nbytes #equal to 'a.size * a.itemsize' 

12

In [21]:
a.size * a.itemsize

12

In [25]:
#3d example 
c = np.array([[[1, 2],[3, 4]], #dont forget this ',' at each square bracket '[]'
              [[4, 5],[7,8]]])
print(c)

[[[1 2]
  [3 4]]

 [[4 5]
  [7 8]]]


In [26]:
#get spefific element, want number (3)
c[0, 1, 0]

3

In [27]:
c[0, 1, :]

array([3, 4])

In [28]:
c[:,1,:]

array([[3, 4],
       [7, 8]])

In [29]:
np.zeros((2,3,4))

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [31]:
np.ones((3,2,3), dtype='int32')

array([[[1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1]]])

In [32]:
np.full((2,4), 77)

array([[77, 77, 77, 77],
       [77, 77, 77, 77]])

In [33]:
np.full_like(a, 3)

array([3, 3, 3])

In [34]:
np.full(a.shape, 3) #same as above

array([3, 3, 3])

In [37]:
np.random.rand(4,2,3)

array([[[0.74243163, 0.8630228 , 0.70386004],
        [0.68408747, 0.78571577, 0.8821172 ]],

       [[0.01609218, 0.57450603, 0.7478284 ],
        [0.89930451, 0.30594239, 0.10139996]],

       [[0.50832054, 0.47521219, 0.37821032],
        [0.62907745, 0.83441258, 0.63275869]],

       [[0.92994367, 0.83135442, 0.3779443 ],
        [0.08517624, 0.79595366, 0.77896753]]])

In [54]:
#random number integer 
np.random.randint(-2, 12, size = (2, 3))

array([[-1,  6,  8],
       [ 4, 10, -2]])

In [55]:
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [62]:
k = np.ones((5,5))
print(k)

zero = np.zeros((3,3))
zero[1,1]=9
print(zero)

k[1:4, 1:4]=zero #remember that last not "included"

print(k) #tadaaaa!!

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]
