In [1]:
import numpy as np

In [3]:
lis = np.array([[1, 2, 3, 4], [5, 6, 7, 8 ]])
lis

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [4]:
# or you could seperate 
lis2 = [[2, 3, 4, 5], [6, 7, 8, 9]]
ary = np.array(lis2)
ary

array([[2, 3, 4, 5],
       [6, 7, 8, 9]])

In [5]:
#numpy impotant on shape, the number of dimensions and data type
print(ary.shape)
print(lis.shape)
print()
print(ary.ndim)
print()
print(lis.dtype)

(2, 4)
(2, 4)

2

int32


In [6]:
#zeros, ones, full

np.zeros((3,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [7]:
np.ones((3,6))

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [8]:
np.full((4,3), 3.147)

array([[3.147, 3.147, 3.147],
       [3.147, 3.147, 3.147],
       [3.147, 3.147, 3.147],
       [3.147, 3.147, 3.147]])

In [11]:
#np.empty not initialize any values
print(np.zeros((4,7)))
np.empty((4,7)) #but use the same value siza that store in memory 

[[0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]


array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.]])

In [14]:
#ranges : use np.arange
np.arange(start = 4, stop = 16, step = 3) # 4 + 3 = 7 and last value, 16 not included

array([ 4,  7, 10, 13])

In [13]:
#if default use start = 0, and step = 1
np.arange(7)

array([0, 1, 2, 3, 4, 5, 6])

In [16]:
#linear space value 
np.linspace(start = 10, stop = 24, num = 14)


array([10.        , 11.07692308, 12.15384615, 13.23076923, 14.30769231,
       15.38461538, 16.46153846, 17.53846154, 18.61538462, 19.69230769,
       20.76923077, 21.84615385, 22.92307692, 24.        ])

In [17]:
#random 
np.random.randint(low = 0, high = 99, size = (4,8))

array([[61, 66, 31, 37, 84,  1, 24, 76],
       [33, 59, 43,  2, 65, 46, 16, 81],
       [ 9, 21, 66, 93, 15,  9, 70, 31],
       [87, 47, 34, 85, 96, 63, 41, 88]])

In [18]:
#matrix creation  np.eye() , np.tri()
np.eye(M=3, N=4)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 0.]])

In [19]:
np.diag([1,2,3,4])

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [20]:
print(np.eye(M=3, N=4, k = -2))
np.diag([1,2,3,4], k = 1)

[[0. 0. 0.]
 [0. 0. 0.]
 [1. 0. 0.]
 [0. 1. 0.]]


array([[0, 1, 0, 0, 0],
       [0, 0, 2, 0, 0],
       [0, 0, 0, 3, 0],
       [0, 0, 0, 0, 4],
       [0, 0, 0, 0, 0]])